# runtime: python
# api_version: 1
# threadsafe: false

# handlers:
#  - url: /
#    static_files: templates/index.html
#    upload: templates/index.html

#  - url: /(.*)
#    static_files: templates/\1
#    upload: templates/(.*)

runtime : python
api_version : 1
threadsafe : false
handlers:
 - url : /.*
   script : main.app
